version: 2.1
orbs:
  maven: circleci/maven@1.4.0
jobs:
  build_and_save:
    machine:
      image: ubuntu-2204:2022.10.2
    environment:
      architecture: "amd64"
      platform: "linux/amd64"
    steps:
      - checkout
      - run: mvn clean install
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: /home/circleci/project/gogas-service/target/gogas-service-1.0-SNAPSHOT.jar
          destination: gogas-service-1.0.jar
      - store_artifacts:
          path: /home/circleci/project/telegram-service/target/telegram-service-1.0-SNAPSHOT.jar
          destination: telegram-service-1.0.jar
workflows:
  maven_test:
    jobs:
      - build_and_save
