version: 2.1

orbs:
  node: circleci/node@4.2.0

jobs:
  build:
    executor: node/default
    steps:
      - run: npm install redoc-cli
      - checkout
      - run: mvn clean package

workflows:
  maven_test:
    jobs:
      - build