version: 2.1
orbs:
  maven: circleci/maven@1.4.0
executors:
  machine_executor_amd64:
    machine:
      image: ubuntu-2204:2022.10.2
    environment:
      architecture: "amd64"
      platform: "linux/amd64"
jobs:
  build_and_save:
    steps:
      - checkout
      - run: mvn clean install
      - store_artifacts:
          path: /home/circleci/project/gogas-service/target/gogas-service-1.0-SNAPSHOT.jar
          destination: gogas-service-1.0.jar
      - store_artifacts:
          path: /home/circleci/project/telegram-service/target/telegram-service-1.0-SNAPSHOT.jar
          destination: telegram-service-1.0.jar
workflows:
  maven_test:
    jobs:
      - build_and_save:
          executor: machine_executor_amd64
