version: 2.1

orbs:
  maven: circleci/maven@1.1.1
  node: circleci/node@4.2.0

jobs:
  build:
    executor: node/default
    steps:
      - run: npm init
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install redoc-cli
      - maven/test:
          command: 'package'

workflows:
  maven_test:
    jobs:
      - build