version: 2.1
orbs:
  maven: circleci/maven@1.4.0
jobs:
  build_and_save:
    machine:
      image: ubuntu-2204:2022.10.2
    environment:
      architecture: "amd64"
      platform: "linux/amd64"
    steps:
      - checkout
      - run: mvn clean install -Dmaven.test.skip=true
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: /home/circleci/project/gogas-service/target/gogas-service-1.0-SNAPSHOT.jar
          destination: gogas-service-1.0.jar
      - store_artifacts:
          path: /home/circleci/project/telegram-service/target/telegram-service-1.0-SNAPSHOT.jar
          destination: telegram-service-1.0.jar
      - add_ssh_keys
      - run:
          name: x
          command: cat /home/circleci/.ssh/id_rsa_51c79b502b36531e540d972640be32e5
      - run:
          name: Deploy over SCP
          command: |
            scp -v -B -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null /home/circleci/project/gogas-service/target/gogas-service-1.0-SNAPSHOT.jar ${SSH_USER}@${SSH_HOST}:/gogas/tmp/
workflows:
  maven_test:
    jobs:
      - build_and_save
